[package]
name = "clashctl"
description = "A CLI to interact with clash RESTful API"
version = "0.1.0"
authors = ["George Miao <gm@miao.dev>"]
rust-version = "1.56"
repository = "https://github.com/George-Miao/clashctl"
license = "MIT"
edition = "2021"
keywords = ["clash", "cli"]
categories = ["command-line-utilities"]

[features]
cli = [
  "clap_generate", 
  "terminal_size", 
  "env_logger",
  "owo-colors", 
  "requestty", 
  "clap", 
  "home",
  "ron"
]

[[bin]]
name = "clashctl"
required-features = ["cli"]

[dependencies]
log        = "0.4.14"
serde_json = "1.0.68"
thiserror  = "1.0.30"
chrono     = { version = "0.4.19", features = ["serde"] }
reqwest    = { version = "0.11.6", features = ["stream"] }
serde      = { version = "1.0.130", features = ["derive"] }
tokio      = { version = "1.12.0", features = ["macros"] }
url        = { version = "2.2.2", features = ["serde"] }
semver     = { version = "1.0.4", features = ["serde"] }

# Dependencies required by CLI
terminal_size = { version = "0.1.17", optional = true }
clap_generate = { version = "3.0.0-beta.5", optional = true }
clap          = { version = "3.0.0-beta.5", optional = true }
owo-colors    = { version = "3.0.1", optional = true }
env_logger    = { version = "0.9.0", optional = true }
requestty     = { version = "0.1.2", optional = true }
home          = { version = "0.5.3", optional = true }
ron           = { version = "0.7.0", optional = true }

[dev-dependencies]
simple_logger = "1.13.0"

