[package]
name = "clashctl"
version = "0.1.0"
edition = "2021"

[features]
cli = ["clap_generate", "clap", "terminal_size", "requestty", "owo-colors", "terminal_size", "env_logger"]

[[bin]]
name = "clashctl"
required-features = ["cli"]

[dependencies]
log = "0.4.14"
serde_json = "1.0.68"
thiserror = "1.0.30"
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = { version = "0.11.6", features = ["stream"] }
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["macros"] }
url = { version = "2.2.2" }
clap = { version = "3.0.0-beta.5", optional = true }
clap_generate = { version = "3.0.0-beta.5", optional = true }
requestty = { version = "0.1.2", optional = true }
owo-colors = { version = "3.0.1", optional = true }
terminal_size = { version = "0.1.17", optional = true }
env_logger = { version = "0.9.0", optional = true }
semver = { version = "1.0.4", features = ["serde"] }

[dev-dependencies]
simple_logger = "1.13.0"

