[package]
name = "clashctl"
version = "0.1.0"
edition = "2021"

[features]
cli = ["clap_generate", "clap"]

[dependencies]
serde_json = "1.0.68"
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = { version = "0.11.6", features = ["stream"] }
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["macros"] }
thiserror = "1.0.30"
clap = { version = "3.0.0-beta.5", optional = true }
clap_generate = { version = "3.0.0-beta.5", optional = true }
requestty = "0.1.2"
url = { version = "2.2.2", features = ["serde"] }
log = "0.4.14"

[[bin]]
name = "clashctl"
required-features = ["cli"]

[dev-dependencies]
simple_logger = "1.13.0"
