[package]
name = "clashctl"
version = "0.1.0"
edition = "2021"

[features]
cli = ["clap"]

[dependencies]
serde_json = "1.0.68"
chrono = { version = "0.4.19", features = ["serde"] }
reqwest = { version = "0.11.6", features = ["stream"] }
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["macros"] }
clap = { version = "3.0.0-beta.5", optional = true }
thiserror = "1.0.30"

[[bin]]
name = "clashctl"
required-features = ["cli"]
