version: 2.1

jobs:
  build:
    docker:
      - image: rustlang/rust:nightly
    steps:
      - checkout
      - run:
          command: |
            cargo build --release --bin clashctl
            mkdir /tmp/clashctl
            cd target/release
            mv clashctl clashctl-tui /tmp/clashctl/
      - store_artifacts:
          path: /tmp/clashctl
