version: 2.1

jobs:
  build: 
    docker:
      - image: cimg/rust:1.57.0
    steps:
      - run: checkout
      - run: 
          command: |
            rustup install nightly
            rustup default nightly
            cargo build --release