name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --features cli --release

      - name: Rename builds
        run: |
          pushd target/release
          rm clashctl.d
          mv clashctl clashctl-${{ runner.os }}
          popd
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/clashctl-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
